baseURL = "/"
languageCode = "en-us"
title = "Shayan Hosseini"
theme = "hugo-xmin"
footnotereturnlinkcontents = "↩"
pygmentsuseclasses = true 

staticDir = ["static"]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
[[menu.main]]
    name = "Fav. Quotes"
    url = "/fav-quotes/"
    weight = 3

[markup.goldmark.renderer]
unsafe= true