baseURL = "/"
languageCode = "en-us"
title = "Shayan Hosseini"
theme = "hugo-xmin"
footnotereturnlinkcontents = "↩"
pygmentsuseclasses = true 
googleAnalytics = "G-QZZ44BM0HD"

staticDir = ["static"]

enableGitInfo = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
[[menu.main]]
    name = "Misc"
    url = "/misc/"
    weight = 4

[markup.goldmark.renderer]
unsafe= true

[params]
keywords = [
    "Shayan Hosseini",
    "Distributed Systems",
    "Go",
    "Golang",
    "Senior Software Engineer",
    "Software Engineer",
    "Python",
    "Django",
    "Kubernetes",
    "Formal Verification",
    "TLA+",
    "Linux",
    "Personal Page",
    "Blog",
    "UBC",
    "ACM ICPC",
    "C++",
    "Algorithms"
]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
